// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMJaXsxGeuNY_eHHrs8YBG05SOEc_mMCk',
    appId: '1:626647175485:web:72e1b700bf886e2c06f554',
    messagingSenderId: '626647175485',
    projectId: 'ecommerceapp-2741a',
    authDomain: 'ecommerceapp-2741a.firebaseapp.com',
    storageBucket: 'ecommerceapp-2741a.appspot.com',
    measurementId: 'G-882Q0Z7M6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQT6jHGP78EW7ef1zENPuFAaBL5CcQu8I',
    appId: '1:626647175485:android:bf7296fc9817cce706f554',
    messagingSenderId: '626647175485',
    projectId: 'ecommerceapp-2741a',
    storageBucket: 'ecommerceapp-2741a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0BDw1VblnelaWDbDMeu0WzmdeU0xR8_Y',
    appId: '1:626647175485:ios:27b39ae5fab88c9806f554',
    messagingSenderId: '626647175485',
    projectId: 'ecommerceapp-2741a',
    storageBucket: 'ecommerceapp-2741a.appspot.com',
    androidClientId: '626647175485-0orih6212pulc32pmbt7bjv5iufcialu.apps.googleusercontent.com',
    iosClientId: '626647175485-h617ss7frg74nq9odl59p7f7avad005b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0BDw1VblnelaWDbDMeu0WzmdeU0xR8_Y',
    appId: '1:626647175485:ios:27b39ae5fab88c9806f554',
    messagingSenderId: '626647175485',
    projectId: 'ecommerceapp-2741a',
    storageBucket: 'ecommerceapp-2741a.appspot.com',
    androidClientId: '626647175485-0orih6212pulc32pmbt7bjv5iufcialu.apps.googleusercontent.com',
    iosClientId: '626647175485-h617ss7frg74nq9odl59p7f7avad005b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMJaXsxGeuNY_eHHrs8YBG05SOEc_mMCk',
    appId: '1:626647175485:web:705e9d17f4c92ab206f554',
    messagingSenderId: '626647175485',
    projectId: 'ecommerceapp-2741a',
    authDomain: 'ecommerceapp-2741a.firebaseapp.com',
    storageBucket: 'ecommerceapp-2741a.appspot.com',
    measurementId: 'G-7Q346RMLZ4',
  );

}